version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "main"
  schedule:
    interval: weekly
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
